! ------------------------------------------------------------------------------
! ROFI Color theme
! User: F0x48
! ------------------------------------------------------------------------------
rofi.color-normal:  #373B41,#F1E7E9,#373B41,#373B41,#EF798A
rofi.modi: window,run
rofi.padding: 14
rofi.color-window:  #373B41,#EF798A
rofi.separator-style: none
rofi.hide-scrollbar: true
rofi.line-margin: 5
rofi.bw: 2
rofi.location:7
rofi.font: Ubuntu Mono 14
rofi.lines: 5
rofi.width: 25 


